name: expense_tracker_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  pluto_grid: ^7.0.2
  riverpod_annotation: ^2.2.1
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
